export const ORDER_SET_TYPE = 'ORDER_SET_TYPE'
export const PAY_SET_METHOD = 'PAY_SET_METHOD'

// category constant
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

// product constant
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT'

//add, remove order
export const ORDER_ADD_ITEM = 'ORDER_ADD_ITEM'
export const REMOVE_FROM_ORDER = 'REMOVE_FROM_ORDER'
export const ORDER_CLEAR = 'ORDER_CLEAR';